export const USER_STATE_CHANGED = "USER_STATE_CHANGED";
export const USERSPOTS_STATE_CHANGED = "USERSPOTS_STATE_CHANGED";

export const SPOTS_STATE_CHANGED = "SPOTS_STATE_CHANGED";
export const CHALLENGES_STATE_CHANGED = "CHALLENGES_STATE_CHANGED";
export const CLEAR_DATA = "CLEAR_DATA";
